import { spawn } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// Auto-generated by Flux Island, paths injected at install time
const NODE_PATH = "/Applications/Flux Island.app/Contents/MacOS/Flux Island";
const BITS_REPORT_BIN = "/Applications/Flux Island.app/Contents/Resources/bin/flux-bits-report";

function getDebugFlag(baseDirectory) {
  try {
    const configPath = join(baseDirectory, '.opencode', 'tea-reporter.config.json');
    if (!existsSync(configPath)) return false;
    const raw = readFileSync(configPath, 'utf8');
    const parsed = JSON.parse(raw);
    return Boolean(parsed && parsed.debug);
  } catch {
    return false;
  }
}

function runHook(baseDirectory, hookName, input, output, debug) {
  return new Promise((resolve) => {
    const args = [
      BITS_REPORT_BIN,
      'opencode',
      hookName,
    ];
    if (debug) args.push('--debug');
    const child = spawn(NODE_PATH, args, {
      stdio: ['pipe', 'ignore', 'ignore'],
      env: { ...process.env, ELECTRON_RUN_AS_NODE: '1' },
    });
    const payload = { input: { ...(input || {}), baseDirectory }, output: output || {} };
    try {
      child.stdin.end(JSON.stringify(payload));
    } catch {
      try {
        child.stdin.end();
      } catch {}
    }
    child.on('close', () => resolve());
    child.on('error', () => resolve());
  });
}

export default function AiCodeReportPlugin({ baseDirectory }) {
  const baseDir = typeof baseDirectory === 'string' && baseDirectory ? baseDirectory : process.cwd();
  const debug = getDebugFlag(baseDir);
  return {
    'tool.execute.before': async (input, output) => {
      const toolName = String(input?.tool || '');
      if (toolName !== 'write') return;
      await runHook(baseDir, 'tool_execute_before', input, output, debug);
    },
    'tool.execute.after': async (input, output) => {
      const toolName = String(input?.tool || '');
      if (toolName !== 'write' && toolName !== 'edit' && toolName !== 'apply_patch') return;
      await runHook(baseDir, 'tool_execute_after', input, output, debug);
    },
  };
}
